protos:
	protoc -I protos/ protos/currency.proto --go_out=protos/currency --go_opt=paths=source_relative

protos_grpc:
	protoc -I protos/ protos/currency.proto --go-grpc_out=protos/currency --go-grpc_opt=paths=source_relative	